# Generated by Django 3.0.4 on 2020-03-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='palceholder.png', upload_to='img'),
            preserve_default=False,
        ),
    ]
