# Generated by Django 3.0.4 on 2020-03-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image2',
            new_name='image',
        ),
    ]
